version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: sistema-db-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: llmapp
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: sistema-backend-1
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_SITE_URL: ${OPENROUTER_SITE_URL}
      OPENROUTER_APP_NAME: ${OPENROUTER_APP_NAME}
      PYTHONUNBUFFERED: "1"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: always


  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: sistema-frontend-1
    environment:
      BACKEND_BASE_URL: "http://backend:8000"
      FLET_SERVER_PORT: "3000"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data:
